name: Build Formula11 Docker Image

on:
  push:
    branches: [master]
    # paths:
    #   - ".gitea/workflows/pocketbase-docker.yaml"
    #   - "pocketbase.dockerfile"

jobs:
  pocketbase-docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: gitea.vps.chriphost.de
          username: ${{ secrets.CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
      - name: Build Formula11 Docker Image
        run: docker build --file formula11.dockerfile --tag gitea.vps.chriphost.de/christoph/formula11:latest .
      - name: Push Formula11 Docker Image
        run: docker push gitea.vps.chriphost.de/christoph/formula11:latest
